### ISSUE TITLE
Nested object references are not retained during instance save

### ISSUE THREAD

**Issue by rywhee** [Swimlane/angular-model-factory#21]
After an instance is saved, the returned value is extended from the server to the instance. This utilizes the shallowClearAndCopy function to update the instance without replacing it. 

```javascript
var shallowClearAndCopy = function(src, dst) {
    dst = dst || {};

    forEach(dst, function (value, key) {
        delete dst[key];
    });

    for (var key in src) {
        if (src.hasOwnProperty(key)) {
            dst[key] = src[key];
        }
    }

    return dst;
};
```
However, this function as-is does not account for nested objects, as _those will be_ replaced and their reference lost; causing a disconnect with the model instance.

**Comment by amcdnl** [comment]
Please provide a breaking test or example data causing this.

**Comment by amcdnl** [comment]
Any updates on this?

**Comment by juristr** [comment]
@rywhee and I were last discussing in PR #22. As discussed there, the problem is in the `shallowClearAndCopy` as far as I understood. If you debug the test which @rywhee adapted to reproduce the issue, then it becomes clear.

**Comment by amcdnl** [comment]
The shallow clear and copy was taken directly from the angular ng-resource code ... This gets really tricky on how you would solve this with arrays and whatnot which is why i resorted to this solution.

https://github.com/angular/angular.js/blob/master/src/ngResource/resource.js#L30
