### ISSUE TITLE
Delete operation should not send body

### ISSUE THREAD

**Issue by olerass** [Swimlane/angular-model-factory#31]
Currently `model.$destroy()` sends the model json along with the DELETE request in the body. This is not supported in the HTTP protocol and may even cause some implementations on the receiving end to fail (how I discovered it).

See http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-14#page-20

**Comment by amcdnl** [comment]
Ah! Good point!

**Comment by juristr** [comment]
ok, will check that out and let you know. Thx for reporting this!

**Comment by juristr** [comment]
@olerass @amcdnl Fixed the bug and pushed a new version v0.2.9 to bower. This should solve the issue. Thx again for reporting it!
