### ISSUE TITLE
Allow to define urls with custom patterns

### ISSUE THREAD

**Issue by juristr** [Swimlane/angular-model-factory#32]
Currently, especially when defining custom actions like

```javascript
module.factory('AnimalModel', function($modelFactory){
   var model = $modelFactory('zoo', {
      actions: {
         customAction: {
            url: 'mycustom',
            ...
         }
      }
   });
``` 

..then using `AnimalModel.mycustom({ id: 123 })` will result in a request that looks like `GET ..zoo/mycustom?id=123`.

It would be cool though, if I could define a custom URL s.t. the request URL becomes `zoo/mycustom/123`. This could be defined by using a pattern matching approach in the URL. So the developer specifies the URL with placeholders...

```javascript
module.factory('AnimalModel', function($modelFactory){
    ...
         customAction: {
            url: 'mycustom/:id',
            ...
         }
    ...
   });
```

... which are then matched against the properties of the passed obj.

**Comment by amcdnl** [comment]
Our matcher doesn't support `:id` annotation.

The override is the closest thing we have to this right now.

**Comment by juristr** [comment]
@amcdnl Ya, I added this issue as a reminder. A work mate of mine suggested this enhancement as he wanted to further customize the url of a custom action. My intention was to actually adjust how the URL is constructed within the `$buildRequest` method.

What do you mean by "The override is the closest thing we have to this right now"?

**Comment by amcdnl** [comment]
There is an overrideUrl param to totally clobber the url and define your own.

**Comment by juristr** [comment]
Oh, didn't even know about that one. Guess I have to continue with improving the docs :)

Do you have an example usage? Otherwise I'll check the src tomorrow at work

**Comment by juristr** [comment]
@amcdnl I'm currently implementing this and wanted to know your opinion on it.

What works so far in my branch is to define a model like

```javascript
angular.module('test-module', ['modelFactory'])
    .factory('PersonModel', function($modelFactory) {
        return $modelFactory('/api/people', {
            actions: {
                getComplexUri: {
                    url: 'child/{id}/some/subpath'
                }
            }
        });
    });
```
..and then invoke it: `PersonModel.getComplexUri({ id: 123 });`. That results in a `GET /api/people/child/123/some/subpath`.

There are some issues with this, though.

To make the above work, I had change the `Model.$url` function s.t. it uses the 

```javascript
new UriTemplate(u).fill(function(varname){
   ...
});
```

instead of the `new UriTemplate(u).fillFromObject(...)` as we have been using so far. This was necessary in order to remove the matched properties from the passed params object and thus to prevent that they're appended to the final URL. Not sure that was understandable :smile: 
The default behavior currently is to do this `uri += '{?param*}';`...basically to append all params to the URI for `GET` requests. Thus, in order to not get `/api/people/child/123/some/subpath?id=123`, I need to make sure that _matched params_ are removed, while non-matched continue to be appended.

This makes the above work, but regression tests for PUT fail. The problem is that when executing a PUT, 

```javascript
someModelInstance.save();
```
... the data of the instance is currently passed to the `Model.$url(...)` function to resolve the endpoint URL. Problem is, that if I remove the matched variables, then, for

```javascript
var newModel = new PersonModel({
                    id: 123,
                    name: 'Juri'
                });
newModel.$save();
```
I'd get
```
GET /api/people/123
BODY:
{ "name": "Juri" }
```

That's obviously wrong as the BODY shouldn't be touched in that case.

This is for sure adjustable with some IF-ELSE, like don't remove params for PUT/POST/DELETE requests...but wanted to know whether  you have a better idea.

(In case, the implementation so far is in branch `allow-custom-url-placeholders`, but it is obviously  **not ready** as the tests don't pass and I have to polish the git history)
