### ISSUE TITLE
Custom actions don't resolve query params properly

### ISSUE THREAD

**Issue by juristr** [Swimlane/angular-model-factory#35]
There's currently a bug in the codebase that prevents query params to be properly resolved into the URL when using custom actions, like when having a custom action

```javascript
angular.module('test-module', ['modelFactory'])
.factory('PersonModel', function($modelFactory) {
    return $modelFactory('/api/people', {
        actions: {
            // static
            queryChildren: {
                type: 'GET',
                url: 'children',
                isArray: true
            }
      }
    });
});
```

..then when invoking

```javascript
PersonModel.queryChildren({
   type: 'minor'
});
```

I'd expect the following URL to be invoked: `/api/people/children?type=minor`. Instead `/api/people/children` gets invoked.

The branch `bug-queryparams-customurls` reproduces the problem with a failing test.

**Comment by juristr** [comment]
Oh..seems this is simply an inconsistency in the docs. If you use the `method` property rather than the `type` property for specifying the HTTP verb, it works.

```javascript
...
queryChildren: {
    // type: 'GET', // <<<<< this won't work
    method: 'GET',
    url: 'children',
    isArray: true
}
...
```

@amcdnl Can you confirm this? Guess you're using `method` in your code as well, right?

**Comment by amcdnl** [comment]
I am :)

**Comment by juristr** [comment]
Ok, so I'll update the inconsistencies in the docs :+1:

**Comment by juristr** [comment]
@amcdnl Still...it would maybe be useful to set the `method` to `GET` by default if the user doesn't specify it. What do you think?

**Comment by amcdnl** [comment]
Agreed.
