### ISSUE TITLE
global is undefined on pageload

### ISSUE THREAD

**Issue by bartvanremortele** [Swimlane/angular-model-factory#38]
Hello,

I'm using your library in my angular application but on startup I always get an error in console which refers to the global variable inside of the inner IIFE.

"Uncaught TypeError: Cannot set property 'ModelFactory' of undefined - L20"

When I debug however I can see that the this keywords is passed in but is undefined inside of the function. 

Any idea how I can resolve this?

**Comment by amcdnl** [comment]
Can you create a plunkr or something to recreate?  I've never seen this before.

**Comment by juristr** [comment]
@bartvanremortele Could you show us some code on how you include the model-factory script?

**Comment by bartvanremortele** [comment]
I created a plunkr which reproduces the issue.
http://plnkr.co/edit/qFjUVU3PncS6dDfiWVOS?p=preview

Everything works like I would expect in my app, it's just that it initially keeps throwing that error.

**Comment by juristr** [comment]
@bartvanremortele awesome, thx for providing a reproducible scenario. I'll look into it and give you some feedback.

**Comment by juristr** [comment]
@bartvanremortele I reproduced the issue locally and implemented a fix in v0.2.10 (which was also released on bower).

Feel free to report back any further issues or clarifications you might encounter in using model-factory :smiley:
