### ISSUE TITLE
Add Gitter webhook for better integration

### ISSUE THREAD

**Issue by juristr** [Swimlane/angular-model-factory#50]
hi @amcdnl ,

could you please integrate the gitter webhook on the repo s.t. merge requests, commits etc.. pop up in our Gitter chatroom? Unfortunately I'm not able to access the repo settings. :smile: 

You find the webhook in the Gitter chatroom under "integrations". I've already added our GitHub repo and generated the webhook key. If you don't see it, ping me, so I'll send it over to you.

Thx!

**Comment by rhutchison** [comment]
@juristr close
