### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by taemon1337** [Swimlane/angular-model-factory#57]
I like what I see and would like to test it out, could you push to npm? ( I can't get bower)

**Comment by amcdnl** [comment]
Sure .. will do this wk

**Comment by juristr** [comment]
@amcdnl If we setup the semantic release plugin, we get npm out of the box. See what I wrote in #55 :wink:

**Comment by juristr** [comment]
Done, we're now officially on npm and bower.
