### ISSUE TITLE
More of a question really!!

### ISSUE THREAD

**Issue by sureshvramani** [Swimlane/angular-model-factory#63]
Hi, 

I came across your library for angularjs model so decided to give it a go, the api service I consume returns the data in this structure
<code>{data: 
                     [
                        {'key':value},
                        {'key':'value'}
                     ]
            }
</code>

due to this I'm getting an error referring to .foreach() function expects array rather object.
<code>
function ModelCollection(value){
              value = value || []; 
                // wrap each obj
                value.forEach(function(v, i){
                    // this should not happen but prevent blow up
</code>

 Is there a config I could use to point out the array like response.data instead of response ? 

Many Thanks,
Suresh

**Comment by juristr** [comment]
Hi, you can use `isArray = false` in the definition of your action method. Just like this test case demonstrates: https://github.com/Swimlane/angular-model-factory/blob/master/test/spec/modelUsage.spec.js#L864

**Comment by sureshvramani** [comment]
Thanks juristr !!
