### ISSUE TITLE
Body of custom POST action method

### ISSUE THREAD

**Issue by juristr** [Swimlane/angular-model-factory#64]
I need your opinion @amcdnl .

When I have a scenario where I want to POST some custom content to `/department/123/changes', I'd probably define a custom action method like the `$saveChanges` below (ignore the names, it's just an example :smiley: ).

```javascript
angular.module('test-module', ['modelFactory'])
            .factory('Department', function($modelFactory) {
                var model = $modelFactory('department', {
                    pk: 'ID',

                    actions: {
                        '$saveChanges': {
                            url: '{id}/changes',
                            method: 'POST'
                        }
                    }
                });

                return model;
            });
```

So I'd use it like

```javascript
var someExistingDepartment = new Department({ id: 123, name: 'Human Resources' });

someExistingDepartment.$saveChanges({ test: 'abc', isValid: true });
```

Currently this executes a

```
POST department/123/changes
{"id":1,"name":"Human Resources"}
```

..which is totally wrong. The action method simply sends the body of the model instance.

I'd rather expect

```
POST department/123/changes
{ "test": "abc", "isValid": true}
```

@amcdnl Do you agree? So I'm going to fix that.

_(In case, a running example with a failing test is in the `fix-custom-post` branch)_

**Comment by amcdnl** [comment]
you could do static method like `Department.$saveChanges(damodel)`.  

I dont think instance level items should pass other instances.

**Comment by juristr** [comment]
fair enough. That'd work.
