### ISSUE TITLE
angular-model-factory is now an abandonware?

### ISSUE THREAD

**Issue by mateusleon** [swimlane/angular-model-factory#78]
Hello there, I've met this project a few days ago and noticed that is really interesting, a real straight forward approach to deal with angular models, but it seems that there's no longer interest to maintain / evolve it.

The docs are missing information, several assumptions I've made looking on the source to understand how the library deals with the data.

Please let me know which are the future aspects of this project, how you are seeing it, and if you will not give to it more attention, can I know why and if is there an alternative for this model layer that you recommend?

Thanks in advance.

**Comment by amcdnl** [comment]
Its still a very functional library and used in our production environment. We are in the process of considering building a Angular2 version but are unsure at this point.

**Comment by mateusleon** [comment]
Thanks for the reply. So. may I as ask you some questions?

1 - Considering nested resources (`resources/{resourceId}/sub-resources/{subResourceId}`), how can I declare them as models, and stabilish their relations (resource HAS_MANY / HAS_ONE sub-resource)?

2 - Every $save action in a nested resource need to inform its path params?

3 - Having a model Dogs, I want to make a batch save, not on each instance. The backend is prepared to receive and array for an open request (POST / PUT to /dogs), and process each object separately. Where do I place this handler and how can I operate over the elements to turn then eligible to send?

4 - Considering the question 3, do you agree that POST and PUT operations over the collections are appliable? (only to have a second opinion to argue with my client).

**Comment by amcdnl** [comment]
1) It doesn't handle relationships.
2) Not sure I follow.
3) It doesn't handle batch operations out of the box
4) It depends on whether its new or updating.
